services:
  web:
    build: ./app
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - .env 
    ports:
      - "8000:8000" 

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - web

volumes:
  postgres_data: