server:
  service:
    type: ClusterIP
  persistentVolume:
    enabled: false

alertmanager:
  service:
    type: ClusterIP
  persistence:
    enabled: false

pushgateway:
  service:
    type: ClusterIP