replicaCount: 2

image:
  repository: 165690630824.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

configMap:
  name: django-app-config
  data:
    DEBUG: "False"
    ALLOWED_HOSTS: "*"
    SECRET_KEY: "django-insecure-demo-key"
    DJANGO_SETTINGS_MODULE: "config.settings"
    PORT: "8000"
    POSTGRES_DB: "postgres"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"

postgres:
  image: "postgres:15"
  port: 5432

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
